/* Master FLOWER's URL law (lane 24, 2026-09-24). What a share link may carry, and nothing more.
   The master reads it at load and tests/flower-url.cjs checks it, so the format has one source
   rather than a parse in the page and a second opinion in a test.

   The law, in full:

   ?view=artwork | schematics | walkthrough   the view the link opens on. Absent means artwork,
                                              which is already the master's opening state.
   &chapter=1…6                               the tour's chapter, read only in the walkthrough.
                                             1-based, because the surface counts that way to a
                                             reader ("Chapter 3 of 6", eyebrow "03 / 06").

   Never carried, and the reason it matters: any dialled value (sets, scales, stroke weights,
   fills, titles, shadow, glow, blends), any pick or hold, the camera's rotation and zoom, and
   the sheet, drawer, fold and hint states. The file owns every value the master holds, so a URL
   carrying them would be a second source of truth beside the master — the drift the August audit
   was about. A link is an entry point, never live state: the address bar is not rewritten as the
   reader moves, and the only URL the master produces is the one the copy control writes.

   A link the law does not allow names nothing. It is read as a whole, so one bad value refuses
   the whole link and the master opens at the artwork view at rest, silently — never a
   half-restored place. Any other parameter is ignored, never interpreted: share links pick up
   tracking extras on their way through chat apps, and the law must not punish that. */
(function (root, factory) {
  const law = factory();
  if (typeof module === 'object' && module.exports) module.exports = law;
  else root.FlowerPlace = law;
})(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';

  /* The three views, resting state first. The master names them in its own data-props; this is
     the name a reader shares. */
  const VIEWS = ['artwork', 'schematics', 'walkthrough'];
  /* The tour's own chapters, not a second count of them: tests/flower-url.cjs asserts this is
     ColourFlower.dc.html's TOUR_PICKS length. */
  const CHAPTERS = 6;
  /* The prop each named view turns on. 'artwork' has none: it is where the master already is. */
  const KEY = { schematics: 'schematicMode', walkthrough: 'walkthroughMode' };

  const REST = {
    view: 'artwork',
    chapter: 1,
    named: false,
    valid: true,
    read: [],
  };

  /* Read a query string into the place it names. Pure: the same string always gives the same
     place, and nothing here touches the document. */
  function read(search) {
    let q;
    try {
      q = new URLSearchParams(search || '');
    } catch (err) {
      return { ...REST, valid: false };
    }
    const rawView = q.get('view');
    const rawChapter = q.get('chapter');
    if (rawView === null && rawChapter === null) return { ...REST };

    const view = rawView === null ? 'artwork' : rawView;
    /* Six values, written as they are shown: '03' and '3.0' are not among them. */
    const chapter = rawChapter === null ? 1 : (/^[1-9]$/.test(rawChapter) ? Number(rawChapter) : NaN);
    const valid = VIEWS.indexOf(view) >= 0 && Number.isInteger(chapter) && chapter >= 1 && chapter <= CHAPTERS;
    return {
      view: valid ? view : 'artwork',
      chapter: valid ? chapter : 1,
      named: true,
      valid,
      /* What the master acts on: the view to enter, and the chapter if the view has one. */
      read: valid && view !== 'artwork' ? [view] : [],
    };
  }

  /* Write the URL for a place — the copy control's own writer, so a link is generated by the
     same law that reads it. The resting place has no URL of its own: the bare page is the
     artwork view. */
  function link(view, chapter) {
    if (view === 'walkthrough') {
      const n = Number(chapter);
      const safe = Number.isInteger(n) && n >= 1 && n <= CHAPTERS ? n : 1;
      return '?view=walkthrough&chapter=' + safe;
    }
    if (view === 'schematics') return '?view=schematics';
    return '';
  }

  /* The chapter a view opens on, and whether the view has chapters at all. */
  function chapterOf(place) {
    return place && place.valid && place.view === 'walkthrough' ? place.chapter : null;
  }

  return { VIEWS, CHAPTERS, KEY, read, link, chapterOf };
});
